### ISSUE TITLE
Move to AtomLinter org?

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-perl#42]
@s-shin Would you be interested in moving this provider to the AtomLinter organization? That way there can be more people working on this, and users (like me, currently) don't have to worry about the project becoming abandoned since there is an organization behind the package that has multiple people able to help maintain it.

If you are interested, there is some detailed documentation available [here](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository), but the gist of it is transfer it to me and I'll put it in the organization and add you as an explicit collaborator 😉.

**Comment by s-shin** [comment]
@Arcanemagus Yes, there is no reason not to do!

I try to transfer this repository to you now.

**Comment by s-shin** [comment]
@Arcanemagus Oh, the transfer failed because there's already [linter-perl repository in your account](https://github.com/Arcanemagus/linter-perl). Could you remove or rename it?

**Comment by s-shin** [comment]
@Arcanemagus  Never mind 😀

However, GitHub now said `Arcanemagus already has a repository in the s-shin/linter-perl network`. The reason might be that the renamed repository is `Forked from s-shin/linter-perl`.

**Comment by Arcanemagus** [comment]
I'll just delete the fork, I have a local clone that I can just change `origin` of anyway.

**Comment by Arcanemagus** [comment]
Done!

**Comment by s-shin** [comment]
Thanks, I did it!

![image](https://user-images.githubusercontent.com/1000800/36322533-ebad8288-1390-11e8-947c-0739519384bf.png)

**Comment by Arcanemagus** [comment]
Transferred over 🎉

Do you want me to update the repo URL in `package.json`?

**Comment by s-shin** [comment]
Great 🎉 

> Do you want me to update the repo URL in package.json?

Yes, please do it 🙇
